### PR TITLE
12784 - Fix rendering of external Text Label images

### LINKED ISSUE #12784: Labels are not rendering HTML that reference external images correctly.
Using VASL 6.6.6.

The following renders correctly in VASSAL 3.6.14:
```
﻿<html> 
<head> <style> body { color: red ; } </style> </head>
xxx 
<img src="https://pacman-ghost.com/images/pacman-ghost.png"> 
yyy
```
vassal-3 6 14

But incorrectly in VASSAL 3.7.0 and 3.7.1:
vassal-3 7 0+1

Remove the `` tag and it renders correctly:
no-img

The `body { color: red ; }` text is CSS, so I suspect the `<head>` and/or `<style>` tags are being removed - broken HTML santitization, triggered by the `` tag...?

### PR DESCRIPTION
**Pull request by Cattlesquat**
Fixes #12784

### CODE REVIEW

File: vassal-app/src/main/java/VASSAL/counters/Labeler.java [hunk 1]
```diff
@@ -618,7 +618,8 @@ public BufferedImage eval() throws Exception {
 
       // paint the foreground
       if (fg != null) {
-        if (txt.contains("<img")) { //NON-NLS
+        // Support images pre-existing in the module
+        if (txt.contains("<img") && !txt.contains("http://") && !txt.contains("https://") && !txt.contains("file://")) { //NON-NLS
```
Comment (uckelman) [inline vassal-app/src/main/java/VASSAL/counters/Labeler.java:622]: I think you might want to match `"src=\"http://"`, etc. just to be safe.

Comment (uckelman) [reply vassal-app/src/main/java/VASSAL/counters/Labeler.java:622]: On reflection, this would be best as a regex, to save checking the string multiple times.

Comment (uckelman) [reply vassal-app/src/main/java/VASSAL/counters/Labeler.java:622]: I think `]+ )? src="(https?|file)://` is the regex we want.

Comment (Cattlesquat) [reply vassal-app/src/main/java/VASSAL/counters/Labeler.java]: done

**Comment by uckelman** [comment]
That last change doesn't work and I'm not sure why not.
