### PR TITLE
10940 - NPE in TurnLevel

### LINKED ISSUE #10940: [Pacific War 2] NullPointerException
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter |  |
| Error Log | [134367 bytes](https://vassalengine.org/files/gh/ad7bf3c08c6d70d10d55e1f20ad1bbbf01090b4f) |

<pre>

Pacific War 2 v0.0 3.6.2

java.lang.NullPointerException: null
 at java.base/java.util.Objects.requireNonNull(Objects.java:208)
 at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
 at java.base/java.util.List.of(List.java:812)
 at VASSAL.build.module.turn.TurnLevel.getPropertyList(TurnLevel.java:409)
</pre>

### PR DESCRIPTION
**Pull request by Cattlesquat**
Fixes #10940 and #10941

### CODE REVIEW

File: vassal-app/src/main/java/VASSAL/build/module/turn/TurnLevel.java [hunk 1]
```diff
@@ -406,6 +407,9 @@ public ComponentI18nData getI18nData() {
    */
   @Override
   public List<String> getPropertyList() {
-    return List.of(propertyName);
+    if (propertyName != null) {
+      return List.of(propertyName);
+    }
+    return Collections.emptyList();
```
Comment (uckelman) [inline vassal-app/src/main/java/VASSAL/build/module/turn/TurnLevel.java:413]: `List.of()` is the same thing and you don't need to import `Collections`, then.

Now more concise and less verbose: :)
```
return propertyName != null ? List.of(propertyName) : List.of();
```

Comment (Cattlesquat) [reply vassal-app/src/main/java/VASSAL/build/module/turn/TurnLevel.java]: done
